# Generated by Django 5.2.4 on 2025-07-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaimAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProcedureCode', models.CharField(max_length=20)),
                ('DiagnosisCode', models.CharField(max_length=20)),
                ('ItemCode', models.CharField(max_length=20)),
                ('ServiceDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicalAidID', models.CharField(editable=False, max_length=10, unique=True)),
                ('MedicalAidName', models.CharField(max_length=100)),
                ('MedicalAidType', models.CharField(max_length=50)),
                ('MedicalAidContactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('MedicalAidEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.CharField(max_length=100)),
                ('DiagnosisDate', models.DateField()),
                ('TreatmentDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.CharField(max_length=11, unique=True)),
                ('PatientFullName', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('PatientEmail', models.EmailField(max_length=254, unique=True)),
                ('PatientPhone', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('MAIN', 'Main Member'), ('DEP', 'Dependent')], default='DEP', max_length=10)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicalaid')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
            options={
                'unique_together': {('patient', 'medical_aid')},
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='api.patient'),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_aids',
            field=models.ManyToManyField(related_name='patients', through='api.PatientMedicalAid', to='api.medicalaid'),
        ),
    ]
