# Generated by Django 5.2.4 on 2025-07-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_claimdetails_medicalaid_medicalhistory_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='Condition',
            new_name='Conditions',
        ),
    ]
