# Generated by Django 5.2.4 on 2025-07-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_condition_medicalhistory_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('disciplineName', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('authirisation', models.BooleanField(default=False)),
                ('claimLimits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providerName', models.CharField(max_length=100)),
                ('providerContactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('providerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('practiceNumber', models.CharField(max_length=20, unique=True)),
                ('practiceAddress', models.TextField(blank=True, null=True)),
                ('disciplineCode', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='Conditions',
            new_name='conditions',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='DiagnosisDate',
            new_name='diagnosisDate',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='TreatmentDetails',
            new_name='treatmentDetails',
        ),
        migrations.RemoveField(
            model_name='medicalaid',
            name='MedicalAidType',
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='PostalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DoctorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('doctorContactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('doctorEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctorSpecialization', models.CharField(blank=True, max_length=100, null=True)),
                ('healthcare_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='api.healthcareprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practiceNumber', models.CharField(max_length=20, unique=True)),
                ('practiceName', models.CharField(max_length=100)),
                ('practiceType', models.CharField(blank=True, max_length=50, null=True)),
                ('providerName', models.CharField(blank=True, max_length=100, null=True)),
                ('practiceAddress', models.TextField(blank=True, null=True)),
                ('practiceContactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('practiceEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=10, null=True)),
                ('disciplineCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_codes', to='api.disciplinecode')),
            ],
        ),
    ]
