# Generated by Django 5.2.4 on 2025-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_disciplinecode_healthcareprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetails',
            name='AdditionalNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='DiagnosisDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='DoctorsName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='PracticeAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='PracticeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='AdditionalNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='MedicalAidPlanName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientAccountNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='PatientAddress',
            field=models.TextField(blank=True, null=True),
        ),
    ]
