# Generated by Django 5.2.4 on 2025-07-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_claimdetails_additionalnotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdetails',
            name='ItemCode',
        ),
        migrations.RemoveField(
            model_name='claimdetails',
            name='ProcedureCode',
        ),
    ]
