# Generated by Django 5.2.4 on 2025-07-25 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_claimdetails_itemcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdetails',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
